import {Product} from './app/shared/models/Product';

export const sample_products: Product[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    price: 10,
    favorite: false,
    description: 'This is from italy',
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 20,
    favorite: true,
    description: 'china itakl',
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 5,
    favorite: false,
    description: 'germany',
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    favorite: true,
    description: 'belgium',
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    favorite: false,
    description: 'asia',
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    favorite: false,
    description: 'italy',
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]

// export const sample_tags:Tag[] = [
//   { name: 'All', count: 6 },
//   { name: 'FastFood', count: 4 },
//   { name: 'Pizza', count: 2 },
//   { name: 'Lunch', count: 3 },
//   { name: 'SlowFood', count: 2 },
//   { name: 'Hamburger', count: 1 },
//   { name: 'Fry', count: 1 },
//   { name: 'Soup', count: 1 },
// ]